// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8cJX1_-svB4CnhUZ5GvAxfO2Elvyec80',
    appId: '1:724666704455:web:c6af6a28dcbf71254e0762',
    messagingSenderId: '724666704455',
    projectId: 'fusechat-a08aa',
    authDomain: 'fusechat-a08aa.firebaseapp.com',
    storageBucket: 'fusechat-a08aa.firebasestorage.app',
    measurementId: 'G-Q5Q0CYP2CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3wCaXxNbOvMeNwycARIhdRojMrKMSXU',
    appId: '1:724666704455:android:16a732775e5d95c34e0762',
    messagingSenderId: '724666704455',
    projectId: 'fusechat-a08aa',
    storageBucket: 'fusechat-a08aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMjY8IvSPkkSXmJD2AJliESZUYrLoIsc',
    appId: '1:724666704455:ios:343389bd2c22eee84e0762',
    messagingSenderId: '724666704455',
    projectId: 'fusechat-a08aa',
    storageBucket: 'fusechat-a08aa.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );
}
